// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgkgameproto.proto

#ifndef PROTOBUF_dgkgameproto_2eproto__INCLUDED
#define PROTOBUF_dgkgameproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace dgkmj {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dgkgameproto_2eproto();
void protobuf_AssignDesc_dgkgameproto_2eproto();
void protobuf_ShutdownFile_dgkgameproto_2eproto();

class AckBroadListentype;
class tagHuinfo;
class tagUserHuInfo;
class tagDianPaoInfo;
class tagGangReturn;
class tagDajiaoReturn;
class tagDgkGameEnd;
class tagOpListenInfo;
class AckCustomiedInfo;
class AckQingInfo;

enum HUGANG {
  HUGANG_ZHIGANG = 2,
  HUGANG_WANGANG = 4,
  HUGANG_ANGANG = 8,
  HUGANG_DIANPAO = 16,
  HUGANG_PAOHU = 32,
  HUGANG_DIANGANG = 64,
  HUGANG_BEIZIMO = 128,
  HUGANG_ZIMO = 256
};
bool HUGANG_IsValid(int value);
const HUGANG HUGANG_MIN = HUGANG_ZHIGANG;
const HUGANG HUGANG_MAX = HUGANG_ZIMO;
const int HUGANG_ARRAYSIZE = HUGANG_MAX + 1;

const ::google::protobuf::EnumDescriptor* HUGANG_descriptor();
inline const ::std::string& HUGANG_Name(HUGANG value) {
  return ::google::protobuf::internal::NameOfEnum(
    HUGANG_descriptor(), value);
}
inline bool HUGANG_Parse(
    const ::std::string& name, HUGANG* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HUGANG>(
    HUGANG_descriptor(), name, value);
}
enum LISTEN_TYPE {
  LISTEN_CARD_NOMAL = 0,
  LISTEN_CARD_BAOTING = 1,
  LISTEN_CARD_BAIPAI = 2,
  LISTEN_CARD_FIRST_BAOPAI = 3
};
bool LISTEN_TYPE_IsValid(int value);
const LISTEN_TYPE LISTEN_TYPE_MIN = LISTEN_CARD_NOMAL;
const LISTEN_TYPE LISTEN_TYPE_MAX = LISTEN_CARD_FIRST_BAOPAI;
const int LISTEN_TYPE_ARRAYSIZE = LISTEN_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* LISTEN_TYPE_descriptor();
inline const ::std::string& LISTEN_TYPE_Name(LISTEN_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    LISTEN_TYPE_descriptor(), value);
}
inline bool LISTEN_TYPE_Parse(
    const ::std::string& name, LISTEN_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LISTEN_TYPE>(
    LISTEN_TYPE_descriptor(), name, value);
}
// ===================================================================

class AckBroadListentype : public ::google::protobuf::Message {
 public:
  AckBroadListentype();
  virtual ~AckBroadListentype();

  AckBroadListentype(const AckBroadListentype& from);

  inline AckBroadListentype& operator=(const AckBroadListentype& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AckBroadListentype& default_instance();

  void Swap(AckBroadListentype* other);

  // implements Message ----------------------------------------------

  AckBroadListentype* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AckBroadListentype& from);
  void MergeFrom(const AckBroadListentype& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 chariid = 1;
  inline bool has_chariid() const;
  inline void clear_chariid();
  static const int kChariidFieldNumber = 1;
  inline ::google::protobuf::int32 chariid() const;
  inline void set_chariid(::google::protobuf::int32 value);

  // optional int32 ListenType = 2;
  inline bool has_listentype() const;
  inline void clear_listentype();
  static const int kListenTypeFieldNumber = 2;
  inline ::google::protobuf::int32 listentype() const;
  inline void set_listentype(::google::protobuf::int32 value);

  // repeated int32 ChangeableCards = 3;
  inline int changeablecards_size() const;
  inline void clear_changeablecards();
  static const int kChangeableCardsFieldNumber = 3;
  inline ::google::protobuf::int32 changeablecards(int index) const;
  inline void set_changeablecards(int index, ::google::protobuf::int32 value);
  inline void add_changeablecards(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      changeablecards() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_changeablecards();

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.AckBroadListentype)
 private:
  inline void set_has_chariid();
  inline void clear_has_chariid();
  inline void set_has_listentype();
  inline void clear_has_listentype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 chariid_;
  ::google::protobuf::int32 listentype_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > changeablecards_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static AckBroadListentype* default_instance_;
};
// -------------------------------------------------------------------

class tagHuinfo : public ::google::protobuf::Message {
 public:
  tagHuinfo();
  virtual ~tagHuinfo();

  tagHuinfo(const tagHuinfo& from);

  inline tagHuinfo& operator=(const tagHuinfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagHuinfo& default_instance();

  void Swap(tagHuinfo* other);

  // implements Message ----------------------------------------------

  tagHuinfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagHuinfo& from);
  void MergeFrom(const tagHuinfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 FanType = 1;
  inline bool has_fantype() const;
  inline void clear_fantype();
  static const int kFanTypeFieldNumber = 1;
  inline ::google::protobuf::int32 fantype() const;
  inline void set_fantype(::google::protobuf::int32 value);

  // optional int32 FanNum = 2;
  inline bool has_fannum() const;
  inline void clear_fannum();
  static const int kFanNumFieldNumber = 2;
  inline ::google::protobuf::int32 fannum() const;
  inline void set_fannum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagHuinfo)
 private:
  inline void set_has_fantype();
  inline void clear_has_fantype();
  inline void set_has_fannum();
  inline void clear_has_fannum();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 fantype_;
  ::google::protobuf::int32 fannum_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagHuinfo* default_instance_;
};
// -------------------------------------------------------------------

class tagUserHuInfo : public ::google::protobuf::Message {
 public:
  tagUserHuInfo();
  virtual ~tagUserHuInfo();

  tagUserHuInfo(const tagUserHuInfo& from);

  inline tagUserHuInfo& operator=(const tagUserHuInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagUserHuInfo& default_instance();

  void Swap(tagUserHuInfo* other);

  // implements Message ----------------------------------------------

  tagUserHuInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagUserHuInfo& from);
  void MergeFrom(const tagUserHuInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 HuTotalscore = 1;
  inline bool has_hutotalscore() const;
  inline void clear_hutotalscore();
  static const int kHuTotalscoreFieldNumber = 1;
  inline ::google::protobuf::int32 hutotalscore() const;
  inline void set_hutotalscore(::google::protobuf::int32 value);

  // repeated .proto.game.dgkmj.tagHuinfo stHuinfo = 2;
  inline int sthuinfo_size() const;
  inline void clear_sthuinfo();
  static const int kStHuinfoFieldNumber = 2;
  inline const ::proto::game::dgkmj::tagHuinfo& sthuinfo(int index) const;
  inline ::proto::game::dgkmj::tagHuinfo* mutable_sthuinfo(int index);
  inline ::proto::game::dgkmj::tagHuinfo* add_sthuinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagHuinfo >&
      sthuinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagHuinfo >*
      mutable_sthuinfo();

  // optional int32 stHupai = 3;
  inline bool has_sthupai() const;
  inline void clear_sthupai();
  static const int kStHupaiFieldNumber = 3;
  inline ::google::protobuf::int32 sthupai() const;
  inline void set_sthupai(::google::protobuf::int32 value);

  // optional int32 stHuType = 4;
  inline bool has_sthutype() const;
  inline void clear_sthutype();
  static const int kStHuTypeFieldNumber = 4;
  inline ::google::protobuf::int32 sthutype() const;
  inline void set_sthutype(::google::protobuf::int32 value);

  // optional int32 stHuFan = 5;
  inline bool has_sthufan() const;
  inline void clear_sthufan();
  static const int kStHuFanFieldNumber = 5;
  inline ::google::protobuf::int32 sthufan() const;
  inline void set_sthufan(::google::protobuf::int32 value);

  // optional int32 stDianPaoSitid = 6;
  inline bool has_stdianpaositid() const;
  inline void clear_stdianpaositid();
  static const int kStDianPaoSitidFieldNumber = 6;
  inline ::google::protobuf::int32 stdianpaositid() const;
  inline void set_stdianpaositid(::google::protobuf::int32 value);

  // optional int32 stDianPaoFan = 7;
  inline bool has_stdianpaofan() const;
  inline void clear_stdianpaofan();
  static const int kStDianPaoFanFieldNumber = 7;
  inline ::google::protobuf::int32 stdianpaofan() const;
  inline void set_stdianpaofan(::google::protobuf::int32 value);

  // optional int32 Sitid = 8;
  inline bool has_sitid() const;
  inline void clear_sitid();
  static const int kSitidFieldNumber = 8;
  inline ::google::protobuf::int32 sitid() const;
  inline void set_sitid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagUserHuInfo)
 private:
  inline void set_has_hutotalscore();
  inline void clear_has_hutotalscore();
  inline void set_has_sthupai();
  inline void clear_has_sthupai();
  inline void set_has_sthutype();
  inline void clear_has_sthutype();
  inline void set_has_sthufan();
  inline void clear_has_sthufan();
  inline void set_has_stdianpaositid();
  inline void clear_has_stdianpaositid();
  inline void set_has_stdianpaofan();
  inline void clear_has_stdianpaofan();
  inline void set_has_sitid();
  inline void clear_has_sitid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagHuinfo > sthuinfo_;
  ::google::protobuf::int32 hutotalscore_;
  ::google::protobuf::int32 sthupai_;
  ::google::protobuf::int32 sthutype_;
  ::google::protobuf::int32 sthufan_;
  ::google::protobuf::int32 stdianpaositid_;
  ::google::protobuf::int32 stdianpaofan_;
  ::google::protobuf::int32 sitid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagUserHuInfo* default_instance_;
};
// -------------------------------------------------------------------

class tagDianPaoInfo : public ::google::protobuf::Message {
 public:
  tagDianPaoInfo();
  virtual ~tagDianPaoInfo();

  tagDianPaoInfo(const tagDianPaoInfo& from);

  inline tagDianPaoInfo& operator=(const tagDianPaoInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagDianPaoInfo& default_instance();

  void Swap(tagDianPaoInfo* other);

  // implements Message ----------------------------------------------

  tagDianPaoInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagDianPaoInfo& from);
  void MergeFrom(const tagDianPaoInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 stCard = 2;
  inline int stcard_size() const;
  inline void clear_stcard();
  static const int kStCardFieldNumber = 2;
  inline ::google::protobuf::int32 stcard(int index) const;
  inline void set_stcard(int index, ::google::protobuf::int32 value);
  inline void add_stcard(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      stcard() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_stcard();

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagDianPaoInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > stcard_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagDianPaoInfo* default_instance_;
};
// -------------------------------------------------------------------

class tagGangReturn : public ::google::protobuf::Message {
 public:
  tagGangReturn();
  virtual ~tagGangReturn();

  tagGangReturn(const tagGangReturn& from);

  inline tagGangReturn& operator=(const tagGangReturn& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagGangReturn& default_instance();

  void Swap(tagGangReturn* other);

  // implements Message ----------------------------------------------

  tagGangReturn* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagGangReturn& from);
  void MergeFrom(const tagGangReturn& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Sitid = 1;
  inline bool has_sitid() const;
  inline void clear_sitid();
  static const int kSitidFieldNumber = 1;
  inline ::google::protobuf::int32 sitid() const;
  inline void set_sitid(::google::protobuf::int32 value);

  // optional int32 stReturnGangscore = 2;
  inline bool has_streturngangscore() const;
  inline void clear_streturngangscore();
  static const int kStReturnGangscoreFieldNumber = 2;
  inline ::google::protobuf::int32 streturngangscore() const;
  inline void set_streturngangscore(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagGangReturn)
 private:
  inline void set_has_sitid();
  inline void clear_has_sitid();
  inline void set_has_streturngangscore();
  inline void clear_has_streturngangscore();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sitid_;
  ::google::protobuf::int32 streturngangscore_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagGangReturn* default_instance_;
};
// -------------------------------------------------------------------

class tagDajiaoReturn : public ::google::protobuf::Message {
 public:
  tagDajiaoReturn();
  virtual ~tagDajiaoReturn();

  tagDajiaoReturn(const tagDajiaoReturn& from);

  inline tagDajiaoReturn& operator=(const tagDajiaoReturn& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagDajiaoReturn& default_instance();

  void Swap(tagDajiaoReturn* other);

  // implements Message ----------------------------------------------

  tagDajiaoReturn* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagDajiaoReturn& from);
  void MergeFrom(const tagDajiaoReturn& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Sitid = 1;
  inline bool has_sitid() const;
  inline void clear_sitid();
  static const int kSitidFieldNumber = 1;
  inline ::google::protobuf::int32 sitid() const;
  inline void set_sitid(::google::protobuf::int32 value);

  // optional int32 stDajiaoscore = 2;
  inline bool has_stdajiaoscore() const;
  inline void clear_stdajiaoscore();
  static const int kStDajiaoscoreFieldNumber = 2;
  inline ::google::protobuf::int32 stdajiaoscore() const;
  inline void set_stdajiaoscore(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagDajiaoReturn)
 private:
  inline void set_has_sitid();
  inline void clear_has_sitid();
  inline void set_has_stdajiaoscore();
  inline void clear_has_stdajiaoscore();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sitid_;
  ::google::protobuf::int32 stdajiaoscore_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagDajiaoReturn* default_instance_;
};
// -------------------------------------------------------------------

class tagDgkGameEnd : public ::google::protobuf::Message {
 public:
  tagDgkGameEnd();
  virtual ~tagDgkGameEnd();

  tagDgkGameEnd(const tagDgkGameEnd& from);

  inline tagDgkGameEnd& operator=(const tagDgkGameEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagDgkGameEnd& default_instance();

  void Swap(tagDgkGameEnd* other);

  // implements Message ----------------------------------------------

  tagDgkGameEnd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagDgkGameEnd& from);
  void MergeFrom(const tagDgkGameEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.game.dgkmj.tagUserHuInfo stUserHu = 1;
  inline int stuserhu_size() const;
  inline void clear_stuserhu();
  static const int kStUserHuFieldNumber = 1;
  inline const ::proto::game::dgkmj::tagUserHuInfo& stuserhu(int index) const;
  inline ::proto::game::dgkmj::tagUserHuInfo* mutable_stuserhu(int index);
  inline ::proto::game::dgkmj::tagUserHuInfo* add_stuserhu();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagUserHuInfo >&
      stuserhu() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagUserHuInfo >*
      mutable_stuserhu();

  // repeated .proto.game.dgkmj.tagDianPaoInfo stDianPaoInfo = 2;
  inline int stdianpaoinfo_size() const;
  inline void clear_stdianpaoinfo();
  static const int kStDianPaoInfoFieldNumber = 2;
  inline const ::proto::game::dgkmj::tagDianPaoInfo& stdianpaoinfo(int index) const;
  inline ::proto::game::dgkmj::tagDianPaoInfo* mutable_stdianpaoinfo(int index);
  inline ::proto::game::dgkmj::tagDianPaoInfo* add_stdianpaoinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDianPaoInfo >&
      stdianpaoinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDianPaoInfo >*
      mutable_stdianpaoinfo();

  // repeated .proto.game.dgkmj.tagDajiaoReturn stDajiaoReturnGang = 3;
  inline int stdajiaoreturngang_size() const;
  inline void clear_stdajiaoreturngang();
  static const int kStDajiaoReturnGangFieldNumber = 3;
  inline const ::proto::game::dgkmj::tagDajiaoReturn& stdajiaoreturngang(int index) const;
  inline ::proto::game::dgkmj::tagDajiaoReturn* mutable_stdajiaoreturngang(int index);
  inline ::proto::game::dgkmj::tagDajiaoReturn* add_stdajiaoreturngang();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDajiaoReturn >&
      stdajiaoreturngang() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDajiaoReturn >*
      mutable_stdajiaoreturngang();

  // repeated .proto.game.dgkmj.tagGangReturn stReturnGang = 4;
  inline int streturngang_size() const;
  inline void clear_streturngang();
  static const int kStReturnGangFieldNumber = 4;
  inline const ::proto::game::dgkmj::tagGangReturn& streturngang(int index) const;
  inline ::proto::game::dgkmj::tagGangReturn* mutable_streturngang(int index);
  inline ::proto::game::dgkmj::tagGangReturn* add_streturngang();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagGangReturn >&
      streturngang() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagGangReturn >*
      mutable_streturngang();

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagDgkGameEnd)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagUserHuInfo > stuserhu_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDianPaoInfo > stdianpaoinfo_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDajiaoReturn > stdajiaoreturngang_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagGangReturn > streturngang_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagDgkGameEnd* default_instance_;
};
// -------------------------------------------------------------------

class tagOpListenInfo : public ::google::protobuf::Message {
 public:
  tagOpListenInfo();
  virtual ~tagOpListenInfo();

  tagOpListenInfo(const tagOpListenInfo& from);

  inline tagOpListenInfo& operator=(const tagOpListenInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tagOpListenInfo& default_instance();

  void Swap(tagOpListenInfo* other);

  // implements Message ----------------------------------------------

  tagOpListenInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tagOpListenInfo& from);
  void MergeFrom(const tagOpListenInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 isHaveOpListen = 1;
  inline bool has_ishaveoplisten() const;
  inline void clear_ishaveoplisten();
  static const int kIsHaveOpListenFieldNumber = 1;
  inline ::google::protobuf::int32 ishaveoplisten() const;
  inline void set_ishaveoplisten(::google::protobuf::int32 value);

  // optional int32 ChairID = 2;
  inline bool has_chairid() const;
  inline void clear_chairid();
  static const int kChairIDFieldNumber = 2;
  inline ::google::protobuf::int32 chairid() const;
  inline void set_chairid(::google::protobuf::int32 value);

  // repeated int32 ChangeableCards = 3;
  inline int changeablecards_size() const;
  inline void clear_changeablecards();
  static const int kChangeableCardsFieldNumber = 3;
  inline ::google::protobuf::int32 changeablecards(int index) const;
  inline void set_changeablecards(int index, ::google::protobuf::int32 value);
  inline void add_changeablecards(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      changeablecards() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_changeablecards();

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.tagOpListenInfo)
 private:
  inline void set_has_ishaveoplisten();
  inline void clear_has_ishaveoplisten();
  inline void set_has_chairid();
  inline void clear_has_chairid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ishaveoplisten_;
  ::google::protobuf::int32 chairid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > changeablecards_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static tagOpListenInfo* default_instance_;
};
// -------------------------------------------------------------------

class AckCustomiedInfo : public ::google::protobuf::Message {
 public:
  AckCustomiedInfo();
  virtual ~AckCustomiedInfo();

  AckCustomiedInfo(const AckCustomiedInfo& from);

  inline AckCustomiedInfo& operator=(const AckCustomiedInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AckCustomiedInfo& default_instance();

  void Swap(AckCustomiedInfo* other);

  // implements Message ----------------------------------------------

  AckCustomiedInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AckCustomiedInfo& from);
  void MergeFrom(const AckCustomiedInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 gametype = 1;
  inline bool has_gametype() const;
  inline void clear_gametype();
  static const int kGametypeFieldNumber = 1;
  inline ::google::protobuf::int32 gametype() const;
  inline void set_gametype(::google::protobuf::int32 value);

  // optional int32 isYipaodouxiang = 2;
  inline bool has_isyipaodouxiang() const;
  inline void clear_isyipaodouxiang();
  static const int kIsYipaodouxiangFieldNumber = 2;
  inline ::google::protobuf::int32 isyipaodouxiang() const;
  inline void set_isyipaodouxiang(::google::protobuf::int32 value);

  // optional int32 isQiangganghu = 3;
  inline bool has_isqiangganghu() const;
  inline void clear_isqiangganghu();
  static const int kIsQiangganghuFieldNumber = 3;
  inline ::google::protobuf::int32 isqiangganghu() const;
  inline void set_isqiangganghu(::google::protobuf::int32 value);

  // optional int32 isChangeCard = 4;
  inline bool has_ischangecard() const;
  inline void clear_ischangecard();
  static const int kIsChangeCardFieldNumber = 4;
  inline ::google::protobuf::int32 ischangecard() const;
  inline void set_ischangecard(::google::protobuf::int32 value);

  // optional int32 isCheckhuazhudajiao = 5;
  inline bool has_ischeckhuazhudajiao() const;
  inline void clear_ischeckhuazhudajiao();
  static const int kIsCheckhuazhudajiaoFieldNumber = 5;
  inline ::google::protobuf::int32 ischeckhuazhudajiao() const;
  inline void set_ischeckhuazhudajiao(::google::protobuf::int32 value);

  // optional int32 isHavePiao = 6;
  inline bool has_ishavepiao() const;
  inline void clear_ishavepiao();
  static const int kIsHavePiaoFieldNumber = 6;
  inline ::google::protobuf::int32 ishavepiao() const;
  inline void set_ishavepiao(::google::protobuf::int32 value);

  // optional int32 piaoTime = 7;
  inline bool has_piaotime() const;
  inline void clear_piaotime();
  static const int kPiaoTimeFieldNumber = 7;
  inline ::google::protobuf::int32 piaotime() const;
  inline void set_piaotime(::google::protobuf::int32 value);

  // repeated int32 UserPiao = 8;
  inline int userpiao_size() const;
  inline void clear_userpiao();
  static const int kUserPiaoFieldNumber = 8;
  inline ::google::protobuf::int32 userpiao(int index) const;
  inline void set_userpiao(int index, ::google::protobuf::int32 value);
  inline void add_userpiao(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      userpiao() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_userpiao();

  // optional int32 IsPiaoyet = 9;
  inline bool has_ispiaoyet() const;
  inline void clear_ispiaoyet();
  static const int kIsPiaoyetFieldNumber = 9;
  inline ::google::protobuf::int32 ispiaoyet() const;
  inline void set_ispiaoyet(::google::protobuf::int32 value);

  // optional int32 RoomType = 10;
  inline bool has_roomtype() const;
  inline void clear_roomtype();
  static const int kRoomTypeFieldNumber = 10;
  inline ::google::protobuf::int32 roomtype() const;
  inline void set_roomtype(::google::protobuf::int32 value);

  // optional int32 ListenType = 11;
  inline bool has_listentype() const;
  inline void clear_listentype();
  static const int kListenTypeFieldNumber = 11;
  inline ::google::protobuf::int32 listentype() const;
  inline void set_listentype(::google::protobuf::int32 value);

  // repeated .proto.game.dgkmj.tagOpListenInfo stOpListen = 12;
  inline int stoplisten_size() const;
  inline void clear_stoplisten();
  static const int kStOpListenFieldNumber = 12;
  inline const ::proto::game::dgkmj::tagOpListenInfo& stoplisten(int index) const;
  inline ::proto::game::dgkmj::tagOpListenInfo* mutable_stoplisten(int index);
  inline ::proto::game::dgkmj::tagOpListenInfo* add_stoplisten();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagOpListenInfo >&
      stoplisten() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagOpListenInfo >*
      mutable_stoplisten();

  // repeated .proto.game.dgkmj.AckQingInfo stQingHuInfo = 13;
  inline int stqinghuinfo_size() const;
  inline void clear_stqinghuinfo();
  static const int kStQingHuInfoFieldNumber = 13;
  inline const ::proto::game::dgkmj::AckQingInfo& stqinghuinfo(int index) const;
  inline ::proto::game::dgkmj::AckQingInfo* mutable_stqinghuinfo(int index);
  inline ::proto::game::dgkmj::AckQingInfo* add_stqinghuinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::AckQingInfo >&
      stqinghuinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::AckQingInfo >*
      mutable_stqinghuinfo();

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.AckCustomiedInfo)
 private:
  inline void set_has_gametype();
  inline void clear_has_gametype();
  inline void set_has_isyipaodouxiang();
  inline void clear_has_isyipaodouxiang();
  inline void set_has_isqiangganghu();
  inline void clear_has_isqiangganghu();
  inline void set_has_ischangecard();
  inline void clear_has_ischangecard();
  inline void set_has_ischeckhuazhudajiao();
  inline void clear_has_ischeckhuazhudajiao();
  inline void set_has_ishavepiao();
  inline void clear_has_ishavepiao();
  inline void set_has_piaotime();
  inline void clear_has_piaotime();
  inline void set_has_ispiaoyet();
  inline void clear_has_ispiaoyet();
  inline void set_has_roomtype();
  inline void clear_has_roomtype();
  inline void set_has_listentype();
  inline void clear_has_listentype();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 gametype_;
  ::google::protobuf::int32 isyipaodouxiang_;
  ::google::protobuf::int32 isqiangganghu_;
  ::google::protobuf::int32 ischangecard_;
  ::google::protobuf::int32 ischeckhuazhudajiao_;
  ::google::protobuf::int32 ishavepiao_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > userpiao_;
  ::google::protobuf::int32 piaotime_;
  ::google::protobuf::int32 ispiaoyet_;
  ::google::protobuf::int32 roomtype_;
  ::google::protobuf::int32 listentype_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagOpListenInfo > stoplisten_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::AckQingInfo > stqinghuinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(13 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static AckCustomiedInfo* default_instance_;
};
// -------------------------------------------------------------------

class AckQingInfo : public ::google::protobuf::Message {
 public:
  AckQingInfo();
  virtual ~AckQingInfo();

  AckQingInfo(const AckQingInfo& from);

  inline AckQingInfo& operator=(const AckQingInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AckQingInfo& default_instance();

  void Swap(AckQingInfo* other);

  // implements Message ----------------------------------------------

  AckQingInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AckQingInfo& from);
  void MergeFrom(const AckQingInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sitid = 1;
  inline bool has_sitid() const;
  inline void clear_sitid();
  static const int kSitidFieldNumber = 1;
  inline ::google::protobuf::int32 sitid() const;
  inline void set_sitid(::google::protobuf::int32 value);

  // optional int32 type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.dgkmj.AckQingInfo)
 private:
  inline void set_has_sitid();
  inline void clear_has_sitid();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 sitid_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_dgkgameproto_2eproto();
  friend void protobuf_AssignDesc_dgkgameproto_2eproto();
  friend void protobuf_ShutdownFile_dgkgameproto_2eproto();

  void InitAsDefaultInstance();
  static AckQingInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// AckBroadListentype

// optional int32 chariid = 1;
inline bool AckBroadListentype::has_chariid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AckBroadListentype::set_has_chariid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AckBroadListentype::clear_has_chariid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AckBroadListentype::clear_chariid() {
  chariid_ = 0;
  clear_has_chariid();
}
inline ::google::protobuf::int32 AckBroadListentype::chariid() const {
  return chariid_;
}
inline void AckBroadListentype::set_chariid(::google::protobuf::int32 value) {
  set_has_chariid();
  chariid_ = value;
}

// optional int32 ListenType = 2;
inline bool AckBroadListentype::has_listentype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AckBroadListentype::set_has_listentype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AckBroadListentype::clear_has_listentype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AckBroadListentype::clear_listentype() {
  listentype_ = 0;
  clear_has_listentype();
}
inline ::google::protobuf::int32 AckBroadListentype::listentype() const {
  return listentype_;
}
inline void AckBroadListentype::set_listentype(::google::protobuf::int32 value) {
  set_has_listentype();
  listentype_ = value;
}

// repeated int32 ChangeableCards = 3;
inline int AckBroadListentype::changeablecards_size() const {
  return changeablecards_.size();
}
inline void AckBroadListentype::clear_changeablecards() {
  changeablecards_.Clear();
}
inline ::google::protobuf::int32 AckBroadListentype::changeablecards(int index) const {
  return changeablecards_.Get(index);
}
inline void AckBroadListentype::set_changeablecards(int index, ::google::protobuf::int32 value) {
  changeablecards_.Set(index, value);
}
inline void AckBroadListentype::add_changeablecards(::google::protobuf::int32 value) {
  changeablecards_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AckBroadListentype::changeablecards() const {
  return changeablecards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AckBroadListentype::mutable_changeablecards() {
  return &changeablecards_;
}

// -------------------------------------------------------------------

// tagHuinfo

// optional int32 FanType = 1;
inline bool tagHuinfo::has_fantype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tagHuinfo::set_has_fantype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tagHuinfo::clear_has_fantype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tagHuinfo::clear_fantype() {
  fantype_ = 0;
  clear_has_fantype();
}
inline ::google::protobuf::int32 tagHuinfo::fantype() const {
  return fantype_;
}
inline void tagHuinfo::set_fantype(::google::protobuf::int32 value) {
  set_has_fantype();
  fantype_ = value;
}

// optional int32 FanNum = 2;
inline bool tagHuinfo::has_fannum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tagHuinfo::set_has_fannum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tagHuinfo::clear_has_fannum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tagHuinfo::clear_fannum() {
  fannum_ = 0;
  clear_has_fannum();
}
inline ::google::protobuf::int32 tagHuinfo::fannum() const {
  return fannum_;
}
inline void tagHuinfo::set_fannum(::google::protobuf::int32 value) {
  set_has_fannum();
  fannum_ = value;
}

// -------------------------------------------------------------------

// tagUserHuInfo

// optional int32 HuTotalscore = 1;
inline bool tagUserHuInfo::has_hutotalscore() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tagUserHuInfo::set_has_hutotalscore() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tagUserHuInfo::clear_has_hutotalscore() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tagUserHuInfo::clear_hutotalscore() {
  hutotalscore_ = 0;
  clear_has_hutotalscore();
}
inline ::google::protobuf::int32 tagUserHuInfo::hutotalscore() const {
  return hutotalscore_;
}
inline void tagUserHuInfo::set_hutotalscore(::google::protobuf::int32 value) {
  set_has_hutotalscore();
  hutotalscore_ = value;
}

// repeated .proto.game.dgkmj.tagHuinfo stHuinfo = 2;
inline int tagUserHuInfo::sthuinfo_size() const {
  return sthuinfo_.size();
}
inline void tagUserHuInfo::clear_sthuinfo() {
  sthuinfo_.Clear();
}
inline const ::proto::game::dgkmj::tagHuinfo& tagUserHuInfo::sthuinfo(int index) const {
  return sthuinfo_.Get(index);
}
inline ::proto::game::dgkmj::tagHuinfo* tagUserHuInfo::mutable_sthuinfo(int index) {
  return sthuinfo_.Mutable(index);
}
inline ::proto::game::dgkmj::tagHuinfo* tagUserHuInfo::add_sthuinfo() {
  return sthuinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagHuinfo >&
tagUserHuInfo::sthuinfo() const {
  return sthuinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagHuinfo >*
tagUserHuInfo::mutable_sthuinfo() {
  return &sthuinfo_;
}

// optional int32 stHupai = 3;
inline bool tagUserHuInfo::has_sthupai() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tagUserHuInfo::set_has_sthupai() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tagUserHuInfo::clear_has_sthupai() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tagUserHuInfo::clear_sthupai() {
  sthupai_ = 0;
  clear_has_sthupai();
}
inline ::google::protobuf::int32 tagUserHuInfo::sthupai() const {
  return sthupai_;
}
inline void tagUserHuInfo::set_sthupai(::google::protobuf::int32 value) {
  set_has_sthupai();
  sthupai_ = value;
}

// optional int32 stHuType = 4;
inline bool tagUserHuInfo::has_sthutype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void tagUserHuInfo::set_has_sthutype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void tagUserHuInfo::clear_has_sthutype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void tagUserHuInfo::clear_sthutype() {
  sthutype_ = 0;
  clear_has_sthutype();
}
inline ::google::protobuf::int32 tagUserHuInfo::sthutype() const {
  return sthutype_;
}
inline void tagUserHuInfo::set_sthutype(::google::protobuf::int32 value) {
  set_has_sthutype();
  sthutype_ = value;
}

// optional int32 stHuFan = 5;
inline bool tagUserHuInfo::has_sthufan() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void tagUserHuInfo::set_has_sthufan() {
  _has_bits_[0] |= 0x00000010u;
}
inline void tagUserHuInfo::clear_has_sthufan() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void tagUserHuInfo::clear_sthufan() {
  sthufan_ = 0;
  clear_has_sthufan();
}
inline ::google::protobuf::int32 tagUserHuInfo::sthufan() const {
  return sthufan_;
}
inline void tagUserHuInfo::set_sthufan(::google::protobuf::int32 value) {
  set_has_sthufan();
  sthufan_ = value;
}

// optional int32 stDianPaoSitid = 6;
inline bool tagUserHuInfo::has_stdianpaositid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void tagUserHuInfo::set_has_stdianpaositid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void tagUserHuInfo::clear_has_stdianpaositid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void tagUserHuInfo::clear_stdianpaositid() {
  stdianpaositid_ = 0;
  clear_has_stdianpaositid();
}
inline ::google::protobuf::int32 tagUserHuInfo::stdianpaositid() const {
  return stdianpaositid_;
}
inline void tagUserHuInfo::set_stdianpaositid(::google::protobuf::int32 value) {
  set_has_stdianpaositid();
  stdianpaositid_ = value;
}

// optional int32 stDianPaoFan = 7;
inline bool tagUserHuInfo::has_stdianpaofan() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void tagUserHuInfo::set_has_stdianpaofan() {
  _has_bits_[0] |= 0x00000040u;
}
inline void tagUserHuInfo::clear_has_stdianpaofan() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void tagUserHuInfo::clear_stdianpaofan() {
  stdianpaofan_ = 0;
  clear_has_stdianpaofan();
}
inline ::google::protobuf::int32 tagUserHuInfo::stdianpaofan() const {
  return stdianpaofan_;
}
inline void tagUserHuInfo::set_stdianpaofan(::google::protobuf::int32 value) {
  set_has_stdianpaofan();
  stdianpaofan_ = value;
}

// optional int32 Sitid = 8;
inline bool tagUserHuInfo::has_sitid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void tagUserHuInfo::set_has_sitid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void tagUserHuInfo::clear_has_sitid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void tagUserHuInfo::clear_sitid() {
  sitid_ = 0;
  clear_has_sitid();
}
inline ::google::protobuf::int32 tagUserHuInfo::sitid() const {
  return sitid_;
}
inline void tagUserHuInfo::set_sitid(::google::protobuf::int32 value) {
  set_has_sitid();
  sitid_ = value;
}

// -------------------------------------------------------------------

// tagDianPaoInfo

// repeated int32 stCard = 2;
inline int tagDianPaoInfo::stcard_size() const {
  return stcard_.size();
}
inline void tagDianPaoInfo::clear_stcard() {
  stcard_.Clear();
}
inline ::google::protobuf::int32 tagDianPaoInfo::stcard(int index) const {
  return stcard_.Get(index);
}
inline void tagDianPaoInfo::set_stcard(int index, ::google::protobuf::int32 value) {
  stcard_.Set(index, value);
}
inline void tagDianPaoInfo::add_stcard(::google::protobuf::int32 value) {
  stcard_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
tagDianPaoInfo::stcard() const {
  return stcard_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
tagDianPaoInfo::mutable_stcard() {
  return &stcard_;
}

// -------------------------------------------------------------------

// tagGangReturn

// optional int32 Sitid = 1;
inline bool tagGangReturn::has_sitid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tagGangReturn::set_has_sitid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tagGangReturn::clear_has_sitid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tagGangReturn::clear_sitid() {
  sitid_ = 0;
  clear_has_sitid();
}
inline ::google::protobuf::int32 tagGangReturn::sitid() const {
  return sitid_;
}
inline void tagGangReturn::set_sitid(::google::protobuf::int32 value) {
  set_has_sitid();
  sitid_ = value;
}

// optional int32 stReturnGangscore = 2;
inline bool tagGangReturn::has_streturngangscore() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tagGangReturn::set_has_streturngangscore() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tagGangReturn::clear_has_streturngangscore() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tagGangReturn::clear_streturngangscore() {
  streturngangscore_ = 0;
  clear_has_streturngangscore();
}
inline ::google::protobuf::int32 tagGangReturn::streturngangscore() const {
  return streturngangscore_;
}
inline void tagGangReturn::set_streturngangscore(::google::protobuf::int32 value) {
  set_has_streturngangscore();
  streturngangscore_ = value;
}

// -------------------------------------------------------------------

// tagDajiaoReturn

// optional int32 Sitid = 1;
inline bool tagDajiaoReturn::has_sitid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tagDajiaoReturn::set_has_sitid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tagDajiaoReturn::clear_has_sitid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tagDajiaoReturn::clear_sitid() {
  sitid_ = 0;
  clear_has_sitid();
}
inline ::google::protobuf::int32 tagDajiaoReturn::sitid() const {
  return sitid_;
}
inline void tagDajiaoReturn::set_sitid(::google::protobuf::int32 value) {
  set_has_sitid();
  sitid_ = value;
}

// optional int32 stDajiaoscore = 2;
inline bool tagDajiaoReturn::has_stdajiaoscore() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tagDajiaoReturn::set_has_stdajiaoscore() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tagDajiaoReturn::clear_has_stdajiaoscore() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tagDajiaoReturn::clear_stdajiaoscore() {
  stdajiaoscore_ = 0;
  clear_has_stdajiaoscore();
}
inline ::google::protobuf::int32 tagDajiaoReturn::stdajiaoscore() const {
  return stdajiaoscore_;
}
inline void tagDajiaoReturn::set_stdajiaoscore(::google::protobuf::int32 value) {
  set_has_stdajiaoscore();
  stdajiaoscore_ = value;
}

// -------------------------------------------------------------------

// tagDgkGameEnd

// repeated .proto.game.dgkmj.tagUserHuInfo stUserHu = 1;
inline int tagDgkGameEnd::stuserhu_size() const {
  return stuserhu_.size();
}
inline void tagDgkGameEnd::clear_stuserhu() {
  stuserhu_.Clear();
}
inline const ::proto::game::dgkmj::tagUserHuInfo& tagDgkGameEnd::stuserhu(int index) const {
  return stuserhu_.Get(index);
}
inline ::proto::game::dgkmj::tagUserHuInfo* tagDgkGameEnd::mutable_stuserhu(int index) {
  return stuserhu_.Mutable(index);
}
inline ::proto::game::dgkmj::tagUserHuInfo* tagDgkGameEnd::add_stuserhu() {
  return stuserhu_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagUserHuInfo >&
tagDgkGameEnd::stuserhu() const {
  return stuserhu_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagUserHuInfo >*
tagDgkGameEnd::mutable_stuserhu() {
  return &stuserhu_;
}

// repeated .proto.game.dgkmj.tagDianPaoInfo stDianPaoInfo = 2;
inline int tagDgkGameEnd::stdianpaoinfo_size() const {
  return stdianpaoinfo_.size();
}
inline void tagDgkGameEnd::clear_stdianpaoinfo() {
  stdianpaoinfo_.Clear();
}
inline const ::proto::game::dgkmj::tagDianPaoInfo& tagDgkGameEnd::stdianpaoinfo(int index) const {
  return stdianpaoinfo_.Get(index);
}
inline ::proto::game::dgkmj::tagDianPaoInfo* tagDgkGameEnd::mutable_stdianpaoinfo(int index) {
  return stdianpaoinfo_.Mutable(index);
}
inline ::proto::game::dgkmj::tagDianPaoInfo* tagDgkGameEnd::add_stdianpaoinfo() {
  return stdianpaoinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDianPaoInfo >&
tagDgkGameEnd::stdianpaoinfo() const {
  return stdianpaoinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDianPaoInfo >*
tagDgkGameEnd::mutable_stdianpaoinfo() {
  return &stdianpaoinfo_;
}

// repeated .proto.game.dgkmj.tagDajiaoReturn stDajiaoReturnGang = 3;
inline int tagDgkGameEnd::stdajiaoreturngang_size() const {
  return stdajiaoreturngang_.size();
}
inline void tagDgkGameEnd::clear_stdajiaoreturngang() {
  stdajiaoreturngang_.Clear();
}
inline const ::proto::game::dgkmj::tagDajiaoReturn& tagDgkGameEnd::stdajiaoreturngang(int index) const {
  return stdajiaoreturngang_.Get(index);
}
inline ::proto::game::dgkmj::tagDajiaoReturn* tagDgkGameEnd::mutable_stdajiaoreturngang(int index) {
  return stdajiaoreturngang_.Mutable(index);
}
inline ::proto::game::dgkmj::tagDajiaoReturn* tagDgkGameEnd::add_stdajiaoreturngang() {
  return stdajiaoreturngang_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDajiaoReturn >&
tagDgkGameEnd::stdajiaoreturngang() const {
  return stdajiaoreturngang_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagDajiaoReturn >*
tagDgkGameEnd::mutable_stdajiaoreturngang() {
  return &stdajiaoreturngang_;
}

// repeated .proto.game.dgkmj.tagGangReturn stReturnGang = 4;
inline int tagDgkGameEnd::streturngang_size() const {
  return streturngang_.size();
}
inline void tagDgkGameEnd::clear_streturngang() {
  streturngang_.Clear();
}
inline const ::proto::game::dgkmj::tagGangReturn& tagDgkGameEnd::streturngang(int index) const {
  return streturngang_.Get(index);
}
inline ::proto::game::dgkmj::tagGangReturn* tagDgkGameEnd::mutable_streturngang(int index) {
  return streturngang_.Mutable(index);
}
inline ::proto::game::dgkmj::tagGangReturn* tagDgkGameEnd::add_streturngang() {
  return streturngang_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagGangReturn >&
tagDgkGameEnd::streturngang() const {
  return streturngang_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagGangReturn >*
tagDgkGameEnd::mutable_streturngang() {
  return &streturngang_;
}

// -------------------------------------------------------------------

// tagOpListenInfo

// optional int32 isHaveOpListen = 1;
inline bool tagOpListenInfo::has_ishaveoplisten() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tagOpListenInfo::set_has_ishaveoplisten() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tagOpListenInfo::clear_has_ishaveoplisten() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tagOpListenInfo::clear_ishaveoplisten() {
  ishaveoplisten_ = 0;
  clear_has_ishaveoplisten();
}
inline ::google::protobuf::int32 tagOpListenInfo::ishaveoplisten() const {
  return ishaveoplisten_;
}
inline void tagOpListenInfo::set_ishaveoplisten(::google::protobuf::int32 value) {
  set_has_ishaveoplisten();
  ishaveoplisten_ = value;
}

// optional int32 ChairID = 2;
inline bool tagOpListenInfo::has_chairid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tagOpListenInfo::set_has_chairid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tagOpListenInfo::clear_has_chairid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tagOpListenInfo::clear_chairid() {
  chairid_ = 0;
  clear_has_chairid();
}
inline ::google::protobuf::int32 tagOpListenInfo::chairid() const {
  return chairid_;
}
inline void tagOpListenInfo::set_chairid(::google::protobuf::int32 value) {
  set_has_chairid();
  chairid_ = value;
}

// repeated int32 ChangeableCards = 3;
inline int tagOpListenInfo::changeablecards_size() const {
  return changeablecards_.size();
}
inline void tagOpListenInfo::clear_changeablecards() {
  changeablecards_.Clear();
}
inline ::google::protobuf::int32 tagOpListenInfo::changeablecards(int index) const {
  return changeablecards_.Get(index);
}
inline void tagOpListenInfo::set_changeablecards(int index, ::google::protobuf::int32 value) {
  changeablecards_.Set(index, value);
}
inline void tagOpListenInfo::add_changeablecards(::google::protobuf::int32 value) {
  changeablecards_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
tagOpListenInfo::changeablecards() const {
  return changeablecards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
tagOpListenInfo::mutable_changeablecards() {
  return &changeablecards_;
}

// -------------------------------------------------------------------

// AckCustomiedInfo

// optional int32 gametype = 1;
inline bool AckCustomiedInfo::has_gametype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AckCustomiedInfo::set_has_gametype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AckCustomiedInfo::clear_has_gametype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AckCustomiedInfo::clear_gametype() {
  gametype_ = 0;
  clear_has_gametype();
}
inline ::google::protobuf::int32 AckCustomiedInfo::gametype() const {
  return gametype_;
}
inline void AckCustomiedInfo::set_gametype(::google::protobuf::int32 value) {
  set_has_gametype();
  gametype_ = value;
}

// optional int32 isYipaodouxiang = 2;
inline bool AckCustomiedInfo::has_isyipaodouxiang() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AckCustomiedInfo::set_has_isyipaodouxiang() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AckCustomiedInfo::clear_has_isyipaodouxiang() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AckCustomiedInfo::clear_isyipaodouxiang() {
  isyipaodouxiang_ = 0;
  clear_has_isyipaodouxiang();
}
inline ::google::protobuf::int32 AckCustomiedInfo::isyipaodouxiang() const {
  return isyipaodouxiang_;
}
inline void AckCustomiedInfo::set_isyipaodouxiang(::google::protobuf::int32 value) {
  set_has_isyipaodouxiang();
  isyipaodouxiang_ = value;
}

// optional int32 isQiangganghu = 3;
inline bool AckCustomiedInfo::has_isqiangganghu() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AckCustomiedInfo::set_has_isqiangganghu() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AckCustomiedInfo::clear_has_isqiangganghu() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AckCustomiedInfo::clear_isqiangganghu() {
  isqiangganghu_ = 0;
  clear_has_isqiangganghu();
}
inline ::google::protobuf::int32 AckCustomiedInfo::isqiangganghu() const {
  return isqiangganghu_;
}
inline void AckCustomiedInfo::set_isqiangganghu(::google::protobuf::int32 value) {
  set_has_isqiangganghu();
  isqiangganghu_ = value;
}

// optional int32 isChangeCard = 4;
inline bool AckCustomiedInfo::has_ischangecard() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AckCustomiedInfo::set_has_ischangecard() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AckCustomiedInfo::clear_has_ischangecard() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AckCustomiedInfo::clear_ischangecard() {
  ischangecard_ = 0;
  clear_has_ischangecard();
}
inline ::google::protobuf::int32 AckCustomiedInfo::ischangecard() const {
  return ischangecard_;
}
inline void AckCustomiedInfo::set_ischangecard(::google::protobuf::int32 value) {
  set_has_ischangecard();
  ischangecard_ = value;
}

// optional int32 isCheckhuazhudajiao = 5;
inline bool AckCustomiedInfo::has_ischeckhuazhudajiao() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AckCustomiedInfo::set_has_ischeckhuazhudajiao() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AckCustomiedInfo::clear_has_ischeckhuazhudajiao() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AckCustomiedInfo::clear_ischeckhuazhudajiao() {
  ischeckhuazhudajiao_ = 0;
  clear_has_ischeckhuazhudajiao();
}
inline ::google::protobuf::int32 AckCustomiedInfo::ischeckhuazhudajiao() const {
  return ischeckhuazhudajiao_;
}
inline void AckCustomiedInfo::set_ischeckhuazhudajiao(::google::protobuf::int32 value) {
  set_has_ischeckhuazhudajiao();
  ischeckhuazhudajiao_ = value;
}

// optional int32 isHavePiao = 6;
inline bool AckCustomiedInfo::has_ishavepiao() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AckCustomiedInfo::set_has_ishavepiao() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AckCustomiedInfo::clear_has_ishavepiao() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AckCustomiedInfo::clear_ishavepiao() {
  ishavepiao_ = 0;
  clear_has_ishavepiao();
}
inline ::google::protobuf::int32 AckCustomiedInfo::ishavepiao() const {
  return ishavepiao_;
}
inline void AckCustomiedInfo::set_ishavepiao(::google::protobuf::int32 value) {
  set_has_ishavepiao();
  ishavepiao_ = value;
}

// optional int32 piaoTime = 7;
inline bool AckCustomiedInfo::has_piaotime() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void AckCustomiedInfo::set_has_piaotime() {
  _has_bits_[0] |= 0x00000040u;
}
inline void AckCustomiedInfo::clear_has_piaotime() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void AckCustomiedInfo::clear_piaotime() {
  piaotime_ = 0;
  clear_has_piaotime();
}
inline ::google::protobuf::int32 AckCustomiedInfo::piaotime() const {
  return piaotime_;
}
inline void AckCustomiedInfo::set_piaotime(::google::protobuf::int32 value) {
  set_has_piaotime();
  piaotime_ = value;
}

// repeated int32 UserPiao = 8;
inline int AckCustomiedInfo::userpiao_size() const {
  return userpiao_.size();
}
inline void AckCustomiedInfo::clear_userpiao() {
  userpiao_.Clear();
}
inline ::google::protobuf::int32 AckCustomiedInfo::userpiao(int index) const {
  return userpiao_.Get(index);
}
inline void AckCustomiedInfo::set_userpiao(int index, ::google::protobuf::int32 value) {
  userpiao_.Set(index, value);
}
inline void AckCustomiedInfo::add_userpiao(::google::protobuf::int32 value) {
  userpiao_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
AckCustomiedInfo::userpiao() const {
  return userpiao_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
AckCustomiedInfo::mutable_userpiao() {
  return &userpiao_;
}

// optional int32 IsPiaoyet = 9;
inline bool AckCustomiedInfo::has_ispiaoyet() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void AckCustomiedInfo::set_has_ispiaoyet() {
  _has_bits_[0] |= 0x00000100u;
}
inline void AckCustomiedInfo::clear_has_ispiaoyet() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void AckCustomiedInfo::clear_ispiaoyet() {
  ispiaoyet_ = 0;
  clear_has_ispiaoyet();
}
inline ::google::protobuf::int32 AckCustomiedInfo::ispiaoyet() const {
  return ispiaoyet_;
}
inline void AckCustomiedInfo::set_ispiaoyet(::google::protobuf::int32 value) {
  set_has_ispiaoyet();
  ispiaoyet_ = value;
}

// optional int32 RoomType = 10;
inline bool AckCustomiedInfo::has_roomtype() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void AckCustomiedInfo::set_has_roomtype() {
  _has_bits_[0] |= 0x00000200u;
}
inline void AckCustomiedInfo::clear_has_roomtype() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void AckCustomiedInfo::clear_roomtype() {
  roomtype_ = 0;
  clear_has_roomtype();
}
inline ::google::protobuf::int32 AckCustomiedInfo::roomtype() const {
  return roomtype_;
}
inline void AckCustomiedInfo::set_roomtype(::google::protobuf::int32 value) {
  set_has_roomtype();
  roomtype_ = value;
}

// optional int32 ListenType = 11;
inline bool AckCustomiedInfo::has_listentype() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void AckCustomiedInfo::set_has_listentype() {
  _has_bits_[0] |= 0x00000400u;
}
inline void AckCustomiedInfo::clear_has_listentype() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void AckCustomiedInfo::clear_listentype() {
  listentype_ = 0;
  clear_has_listentype();
}
inline ::google::protobuf::int32 AckCustomiedInfo::listentype() const {
  return listentype_;
}
inline void AckCustomiedInfo::set_listentype(::google::protobuf::int32 value) {
  set_has_listentype();
  listentype_ = value;
}

// repeated .proto.game.dgkmj.tagOpListenInfo stOpListen = 12;
inline int AckCustomiedInfo::stoplisten_size() const {
  return stoplisten_.size();
}
inline void AckCustomiedInfo::clear_stoplisten() {
  stoplisten_.Clear();
}
inline const ::proto::game::dgkmj::tagOpListenInfo& AckCustomiedInfo::stoplisten(int index) const {
  return stoplisten_.Get(index);
}
inline ::proto::game::dgkmj::tagOpListenInfo* AckCustomiedInfo::mutable_stoplisten(int index) {
  return stoplisten_.Mutable(index);
}
inline ::proto::game::dgkmj::tagOpListenInfo* AckCustomiedInfo::add_stoplisten() {
  return stoplisten_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagOpListenInfo >&
AckCustomiedInfo::stoplisten() const {
  return stoplisten_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::tagOpListenInfo >*
AckCustomiedInfo::mutable_stoplisten() {
  return &stoplisten_;
}

// repeated .proto.game.dgkmj.AckQingInfo stQingHuInfo = 13;
inline int AckCustomiedInfo::stqinghuinfo_size() const {
  return stqinghuinfo_.size();
}
inline void AckCustomiedInfo::clear_stqinghuinfo() {
  stqinghuinfo_.Clear();
}
inline const ::proto::game::dgkmj::AckQingInfo& AckCustomiedInfo::stqinghuinfo(int index) const {
  return stqinghuinfo_.Get(index);
}
inline ::proto::game::dgkmj::AckQingInfo* AckCustomiedInfo::mutable_stqinghuinfo(int index) {
  return stqinghuinfo_.Mutable(index);
}
inline ::proto::game::dgkmj::AckQingInfo* AckCustomiedInfo::add_stqinghuinfo() {
  return stqinghuinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::AckQingInfo >&
AckCustomiedInfo::stqinghuinfo() const {
  return stqinghuinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::dgkmj::AckQingInfo >*
AckCustomiedInfo::mutable_stqinghuinfo() {
  return &stqinghuinfo_;
}

// -------------------------------------------------------------------

// AckQingInfo

// optional int32 sitid = 1;
inline bool AckQingInfo::has_sitid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AckQingInfo::set_has_sitid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AckQingInfo::clear_has_sitid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AckQingInfo::clear_sitid() {
  sitid_ = 0;
  clear_has_sitid();
}
inline ::google::protobuf::int32 AckQingInfo::sitid() const {
  return sitid_;
}
inline void AckQingInfo::set_sitid(::google::protobuf::int32 value) {
  set_has_sitid();
  sitid_ = value;
}

// optional int32 type = 2;
inline bool AckQingInfo::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AckQingInfo::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AckQingInfo::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AckQingInfo::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 AckQingInfo::type() const {
  return type_;
}
inline void AckQingInfo::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dgkmj
}  // namespace game
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::game::dgkmj::HUGANG>() {
  return ::proto::game::dgkmj::HUGANG_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::game::dgkmj::LISTEN_TYPE>() {
  return ::proto::game::dgkmj::LISTEN_TYPE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dgkgameproto_2eproto__INCLUDED
