// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xixiahuashuigameproto.proto

#ifndef PROTOBUF_xixiahuashuigameproto_2eproto__INCLUDED
#define PROTOBUF_xixiahuashuigameproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace xixiahuashuimj {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_xixiahuashuigameproto_2eproto();
void protobuf_AssignDesc_xixiahuashuigameproto_2eproto();
void protobuf_ShutdownFile_xixiahuashuigameproto_2eproto();

class XiXiaHuaShuiGameEnd;

// ===================================================================

class XiXiaHuaShuiGameEnd : public ::google::protobuf::Message {
 public:
  XiXiaHuaShuiGameEnd();
  virtual ~XiXiaHuaShuiGameEnd();

  XiXiaHuaShuiGameEnd(const XiXiaHuaShuiGameEnd& from);

  inline XiXiaHuaShuiGameEnd& operator=(const XiXiaHuaShuiGameEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const XiXiaHuaShuiGameEnd& default_instance();

  void Swap(XiXiaHuaShuiGameEnd* other);

  // implements Message ----------------------------------------------

  XiXiaHuaShuiGameEnd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const XiXiaHuaShuiGameEnd& from);
  void MergeFrom(const XiXiaHuaShuiGameEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 huangzhuang = 1;
  inline int huangzhuang_size() const;
  inline void clear_huangzhuang();
  static const int kHuangzhuangFieldNumber = 1;
  inline ::google::protobuf::int32 huangzhuang(int index) const;
  inline void set_huangzhuang(int index, ::google::protobuf::int32 value);
  inline void add_huangzhuang(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      huangzhuang() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_huangzhuang();

  // repeated int32 genzhuang = 2;
  inline int genzhuang_size() const;
  inline void clear_genzhuang();
  static const int kGenzhuangFieldNumber = 2;
  inline ::google::protobuf::int32 genzhuang(int index) const;
  inline void set_genzhuang(int index, ::google::protobuf::int32 value);
  inline void add_genzhuang(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      genzhuang() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_genzhuang();

  // @@protoc_insertion_point(class_scope:proto.game.xixiahuashuimj.XiXiaHuaShuiGameEnd)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > huangzhuang_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > genzhuang_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_xixiahuashuigameproto_2eproto();
  friend void protobuf_AssignDesc_xixiahuashuigameproto_2eproto();
  friend void protobuf_ShutdownFile_xixiahuashuigameproto_2eproto();

  void InitAsDefaultInstance();
  static XiXiaHuaShuiGameEnd* default_instance_;
};
// ===================================================================


// ===================================================================

// XiXiaHuaShuiGameEnd

// repeated int32 huangzhuang = 1;
inline int XiXiaHuaShuiGameEnd::huangzhuang_size() const {
  return huangzhuang_.size();
}
inline void XiXiaHuaShuiGameEnd::clear_huangzhuang() {
  huangzhuang_.Clear();
}
inline ::google::protobuf::int32 XiXiaHuaShuiGameEnd::huangzhuang(int index) const {
  return huangzhuang_.Get(index);
}
inline void XiXiaHuaShuiGameEnd::set_huangzhuang(int index, ::google::protobuf::int32 value) {
  huangzhuang_.Set(index, value);
}
inline void XiXiaHuaShuiGameEnd::add_huangzhuang(::google::protobuf::int32 value) {
  huangzhuang_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
XiXiaHuaShuiGameEnd::huangzhuang() const {
  return huangzhuang_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
XiXiaHuaShuiGameEnd::mutable_huangzhuang() {
  return &huangzhuang_;
}

// repeated int32 genzhuang = 2;
inline int XiXiaHuaShuiGameEnd::genzhuang_size() const {
  return genzhuang_.size();
}
inline void XiXiaHuaShuiGameEnd::clear_genzhuang() {
  genzhuang_.Clear();
}
inline ::google::protobuf::int32 XiXiaHuaShuiGameEnd::genzhuang(int index) const {
  return genzhuang_.Get(index);
}
inline void XiXiaHuaShuiGameEnd::set_genzhuang(int index, ::google::protobuf::int32 value) {
  genzhuang_.Set(index, value);
}
inline void XiXiaHuaShuiGameEnd::add_genzhuang(::google::protobuf::int32 value) {
  genzhuang_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
XiXiaHuaShuiGameEnd::genzhuang() const {
  return genzhuang_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
XiXiaHuaShuiGameEnd::mutable_genzhuang() {
  return &genzhuang_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace xixiahuashuimj
}  // namespace game
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_xixiahuashuigameproto_2eproto__INCLUDED
