// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: baohu.proto

#ifndef PROTOBUF_baohu_2eproto__INCLUDED
#define PROTOBUF_baohu_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace baohu {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_baohu_2eproto();
void protobuf_AssignDesc_baohu_2eproto();
void protobuf_ShutdownFile_baohu_2eproto();

class GangScore;
class GangInfo;
class BaoHuGameEnd;

// ===================================================================

class GangScore : public ::google::protobuf::Message {
 public:
  GangScore();
  virtual ~GangScore();

  GangScore(const GangScore& from);

  inline GangScore& operator=(const GangScore& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GangScore& default_instance();

  void Swap(GangScore* other);

  // implements Message ----------------------------------------------

  GangScore* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GangScore& from);
  void MergeFrom(const GangScore& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 GangType = 1;
  inline bool has_gangtype() const;
  inline void clear_gangtype();
  static const int kGangTypeFieldNumber = 1;
  inline ::google::protobuf::int32 gangtype() const;
  inline void set_gangtype(::google::protobuf::int32 value);

  // repeated int32 GangCard = 2;
  inline int gangcard_size() const;
  inline void clear_gangcard();
  static const int kGangCardFieldNumber = 2;
  inline ::google::protobuf::int32 gangcard(int index) const;
  inline void set_gangcard(int index, ::google::protobuf::int32 value);
  inline void add_gangcard(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      gangcard() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_gangcard();

  // required int32 gang_score = 3;
  inline bool has_gang_score() const;
  inline void clear_gang_score();
  static const int kGangScoreFieldNumber = 3;
  inline ::google::protobuf::int32 gang_score() const;
  inline void set_gang_score(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.game.baohu.GangScore)
 private:
  inline void set_has_gangtype();
  inline void clear_has_gangtype();
  inline void set_has_gang_score();
  inline void clear_has_gang_score();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > gangcard_;
  ::google::protobuf::int32 gangtype_;
  ::google::protobuf::int32 gang_score_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_baohu_2eproto();
  friend void protobuf_AssignDesc_baohu_2eproto();
  friend void protobuf_ShutdownFile_baohu_2eproto();

  void InitAsDefaultInstance();
  static GangScore* default_instance_;
};
// -------------------------------------------------------------------

class GangInfo : public ::google::protobuf::Message {
 public:
  GangInfo();
  virtual ~GangInfo();

  GangInfo(const GangInfo& from);

  inline GangInfo& operator=(const GangInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GangInfo& default_instance();

  void Swap(GangInfo* other);

  // implements Message ----------------------------------------------

  GangInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GangInfo& from);
  void MergeFrom(const GangInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto.game.baohu.GangScore scoreinfo = 1;
  inline int scoreinfo_size() const;
  inline void clear_scoreinfo();
  static const int kScoreinfoFieldNumber = 1;
  inline const ::proto::game::baohu::GangScore& scoreinfo(int index) const;
  inline ::proto::game::baohu::GangScore* mutable_scoreinfo(int index);
  inline ::proto::game::baohu::GangScore* add_scoreinfo();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangScore >&
      scoreinfo() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangScore >*
      mutable_scoreinfo();

  // @@protoc_insertion_point(class_scope:proto.game.baohu.GangInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangScore > scoreinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_baohu_2eproto();
  friend void protobuf_AssignDesc_baohu_2eproto();
  friend void protobuf_ShutdownFile_baohu_2eproto();

  void InitAsDefaultInstance();
  static GangInfo* default_instance_;
};
// -------------------------------------------------------------------

class BaoHuGameEnd : public ::google::protobuf::Message {
 public:
  BaoHuGameEnd();
  virtual ~BaoHuGameEnd();

  BaoHuGameEnd(const BaoHuGameEnd& from);

  inline BaoHuGameEnd& operator=(const BaoHuGameEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaoHuGameEnd& default_instance();

  void Swap(BaoHuGameEnd* other);

  // implements Message ----------------------------------------------

  BaoHuGameEnd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaoHuGameEnd& from);
  void MergeFrom(const BaoHuGameEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 hufen = 1;
  inline int hufen_size() const;
  inline void clear_hufen();
  static const int kHufenFieldNumber = 1;
  inline ::google::protobuf::int32 hufen(int index) const;
  inline void set_hufen(int index, ::google::protobuf::int32 value);
  inline void add_hufen(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      hufen() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_hufen();

  // repeated .proto.game.baohu.GangInfo gangfen = 2;
  inline int gangfen_size() const;
  inline void clear_gangfen();
  static const int kGangfenFieldNumber = 2;
  inline const ::proto::game::baohu::GangInfo& gangfen(int index) const;
  inline ::proto::game::baohu::GangInfo* mutable_gangfen(int index);
  inline ::proto::game::baohu::GangInfo* add_gangfen();
  inline const ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangInfo >&
      gangfen() const;
  inline ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangInfo >*
      mutable_gangfen();

  // repeated int32 niaofen = 3;
  inline int niaofen_size() const;
  inline void clear_niaofen();
  static const int kNiaofenFieldNumber = 3;
  inline ::google::protobuf::int32 niaofen(int index) const;
  inline void set_niaofen(int index, ::google::protobuf::int32 value);
  inline void add_niaofen(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      niaofen() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_niaofen();

  // repeated int32 lianzhuangfen = 4;
  inline int lianzhuangfen_size() const;
  inline void clear_lianzhuangfen();
  static const int kLianzhuangfenFieldNumber = 4;
  inline ::google::protobuf::int32 lianzhuangfen(int index) const;
  inline void set_lianzhuangfen(int index, ::google::protobuf::int32 value);
  inline void add_lianzhuangfen(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      lianzhuangfen() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_lianzhuangfen();

  // @@protoc_insertion_point(class_scope:proto.game.baohu.BaoHuGameEnd)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > hufen_;
  ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangInfo > gangfen_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > niaofen_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > lianzhuangfen_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_baohu_2eproto();
  friend void protobuf_AssignDesc_baohu_2eproto();
  friend void protobuf_ShutdownFile_baohu_2eproto();

  void InitAsDefaultInstance();
  static BaoHuGameEnd* default_instance_;
};
// ===================================================================


// ===================================================================

// GangScore

// required int32 GangType = 1;
inline bool GangScore::has_gangtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GangScore::set_has_gangtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GangScore::clear_has_gangtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GangScore::clear_gangtype() {
  gangtype_ = 0;
  clear_has_gangtype();
}
inline ::google::protobuf::int32 GangScore::gangtype() const {
  return gangtype_;
}
inline void GangScore::set_gangtype(::google::protobuf::int32 value) {
  set_has_gangtype();
  gangtype_ = value;
}

// repeated int32 GangCard = 2;
inline int GangScore::gangcard_size() const {
  return gangcard_.size();
}
inline void GangScore::clear_gangcard() {
  gangcard_.Clear();
}
inline ::google::protobuf::int32 GangScore::gangcard(int index) const {
  return gangcard_.Get(index);
}
inline void GangScore::set_gangcard(int index, ::google::protobuf::int32 value) {
  gangcard_.Set(index, value);
}
inline void GangScore::add_gangcard(::google::protobuf::int32 value) {
  gangcard_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GangScore::gangcard() const {
  return gangcard_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GangScore::mutable_gangcard() {
  return &gangcard_;
}

// required int32 gang_score = 3;
inline bool GangScore::has_gang_score() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GangScore::set_has_gang_score() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GangScore::clear_has_gang_score() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GangScore::clear_gang_score() {
  gang_score_ = 0;
  clear_has_gang_score();
}
inline ::google::protobuf::int32 GangScore::gang_score() const {
  return gang_score_;
}
inline void GangScore::set_gang_score(::google::protobuf::int32 value) {
  set_has_gang_score();
  gang_score_ = value;
}

// -------------------------------------------------------------------

// GangInfo

// repeated .proto.game.baohu.GangScore scoreinfo = 1;
inline int GangInfo::scoreinfo_size() const {
  return scoreinfo_.size();
}
inline void GangInfo::clear_scoreinfo() {
  scoreinfo_.Clear();
}
inline const ::proto::game::baohu::GangScore& GangInfo::scoreinfo(int index) const {
  return scoreinfo_.Get(index);
}
inline ::proto::game::baohu::GangScore* GangInfo::mutable_scoreinfo(int index) {
  return scoreinfo_.Mutable(index);
}
inline ::proto::game::baohu::GangScore* GangInfo::add_scoreinfo() {
  return scoreinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangScore >&
GangInfo::scoreinfo() const {
  return scoreinfo_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangScore >*
GangInfo::mutable_scoreinfo() {
  return &scoreinfo_;
}

// -------------------------------------------------------------------

// BaoHuGameEnd

// repeated int32 hufen = 1;
inline int BaoHuGameEnd::hufen_size() const {
  return hufen_.size();
}
inline void BaoHuGameEnd::clear_hufen() {
  hufen_.Clear();
}
inline ::google::protobuf::int32 BaoHuGameEnd::hufen(int index) const {
  return hufen_.Get(index);
}
inline void BaoHuGameEnd::set_hufen(int index, ::google::protobuf::int32 value) {
  hufen_.Set(index, value);
}
inline void BaoHuGameEnd::add_hufen(::google::protobuf::int32 value) {
  hufen_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BaoHuGameEnd::hufen() const {
  return hufen_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BaoHuGameEnd::mutable_hufen() {
  return &hufen_;
}

// repeated .proto.game.baohu.GangInfo gangfen = 2;
inline int BaoHuGameEnd::gangfen_size() const {
  return gangfen_.size();
}
inline void BaoHuGameEnd::clear_gangfen() {
  gangfen_.Clear();
}
inline const ::proto::game::baohu::GangInfo& BaoHuGameEnd::gangfen(int index) const {
  return gangfen_.Get(index);
}
inline ::proto::game::baohu::GangInfo* BaoHuGameEnd::mutable_gangfen(int index) {
  return gangfen_.Mutable(index);
}
inline ::proto::game::baohu::GangInfo* BaoHuGameEnd::add_gangfen() {
  return gangfen_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangInfo >&
BaoHuGameEnd::gangfen() const {
  return gangfen_;
}
inline ::google::protobuf::RepeatedPtrField< ::proto::game::baohu::GangInfo >*
BaoHuGameEnd::mutable_gangfen() {
  return &gangfen_;
}

// repeated int32 niaofen = 3;
inline int BaoHuGameEnd::niaofen_size() const {
  return niaofen_.size();
}
inline void BaoHuGameEnd::clear_niaofen() {
  niaofen_.Clear();
}
inline ::google::protobuf::int32 BaoHuGameEnd::niaofen(int index) const {
  return niaofen_.Get(index);
}
inline void BaoHuGameEnd::set_niaofen(int index, ::google::protobuf::int32 value) {
  niaofen_.Set(index, value);
}
inline void BaoHuGameEnd::add_niaofen(::google::protobuf::int32 value) {
  niaofen_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BaoHuGameEnd::niaofen() const {
  return niaofen_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BaoHuGameEnd::mutable_niaofen() {
  return &niaofen_;
}

// repeated int32 lianzhuangfen = 4;
inline int BaoHuGameEnd::lianzhuangfen_size() const {
  return lianzhuangfen_.size();
}
inline void BaoHuGameEnd::clear_lianzhuangfen() {
  lianzhuangfen_.Clear();
}
inline ::google::protobuf::int32 BaoHuGameEnd::lianzhuangfen(int index) const {
  return lianzhuangfen_.Get(index);
}
inline void BaoHuGameEnd::set_lianzhuangfen(int index, ::google::protobuf::int32 value) {
  lianzhuangfen_.Set(index, value);
}
inline void BaoHuGameEnd::add_lianzhuangfen(::google::protobuf::int32 value) {
  lianzhuangfen_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BaoHuGameEnd::lianzhuangfen() const {
  return lianzhuangfen_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BaoHuGameEnd::mutable_lianzhuangfen() {
  return &lianzhuangfen_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace baohu
}  // namespace game
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_baohu_2eproto__INCLUDED
