// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dongxiang.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dongxiang.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace dongxiang {

namespace {

const ::google::protobuf::Descriptor* DongXiangGameEnd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DongXiangGameEnd_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dongxiang_2eproto() {
  protobuf_AddDesc_dongxiang_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dongxiang.proto");
  GOOGLE_CHECK(file != NULL);
  DongXiangGameEnd_descriptor_ = file->message_type(0);
  static const int DongXiangGameEnd_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, hufen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, genzhuangfen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, shaozhuangfen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, mapaifen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, jingfen_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, gangfen_),
  };
  DongXiangGameEnd_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DongXiangGameEnd_descriptor_,
      DongXiangGameEnd::default_instance_,
      DongXiangGameEnd_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DongXiangGameEnd, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DongXiangGameEnd));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dongxiang_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DongXiangGameEnd_descriptor_, &DongXiangGameEnd::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dongxiang_2eproto() {
  delete DongXiangGameEnd::default_instance_;
  delete DongXiangGameEnd_reflection_;
}

void protobuf_AddDesc_dongxiang_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017dongxiang.proto\022\024proto.game.dongxiang\""
    "\202\001\n\020DongXiangGameEnd\022\r\n\005hufen\030\001 \003(\005\022\024\n\014g"
    "enzhuangfen\030\002 \003(\005\022\025\n\rshaozhuangfen\030\003 \003(\005"
    "\022\020\n\010mapaifen\030\004 \003(\005\022\017\n\007jingfen\030\005 \003(\005\022\017\n\007g"
    "angfen\030\006 \003(\005", 172);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dongxiang.proto", &protobuf_RegisterTypes);
  DongXiangGameEnd::default_instance_ = new DongXiangGameEnd();
  DongXiangGameEnd::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dongxiang_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dongxiang_2eproto {
  StaticDescriptorInitializer_dongxiang_2eproto() {
    protobuf_AddDesc_dongxiang_2eproto();
  }
} static_descriptor_initializer_dongxiang_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DongXiangGameEnd::kHufenFieldNumber;
const int DongXiangGameEnd::kGenzhuangfenFieldNumber;
const int DongXiangGameEnd::kShaozhuangfenFieldNumber;
const int DongXiangGameEnd::kMapaifenFieldNumber;
const int DongXiangGameEnd::kJingfenFieldNumber;
const int DongXiangGameEnd::kGangfenFieldNumber;
#endif  // !_MSC_VER

DongXiangGameEnd::DongXiangGameEnd()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DongXiangGameEnd::InitAsDefaultInstance() {
}

DongXiangGameEnd::DongXiangGameEnd(const DongXiangGameEnd& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DongXiangGameEnd::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DongXiangGameEnd::~DongXiangGameEnd() {
  SharedDtor();
}

void DongXiangGameEnd::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DongXiangGameEnd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DongXiangGameEnd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DongXiangGameEnd_descriptor_;
}

const DongXiangGameEnd& DongXiangGameEnd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dongxiang_2eproto();
  return *default_instance_;
}

DongXiangGameEnd* DongXiangGameEnd::default_instance_ = NULL;

DongXiangGameEnd* DongXiangGameEnd::New() const {
  return new DongXiangGameEnd;
}

void DongXiangGameEnd::Clear() {
  hufen_.Clear();
  genzhuangfen_.Clear();
  shaozhuangfen_.Clear();
  mapaifen_.Clear();
  jingfen_.Clear();
  gangfen_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DongXiangGameEnd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 hufen = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hufen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_hufen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_hufen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_hufen;
        if (input->ExpectTag(16)) goto parse_genzhuangfen;
        break;
      }

      // repeated int32 genzhuangfen = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_genzhuangfen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_genzhuangfen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_genzhuangfen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_genzhuangfen;
        if (input->ExpectTag(24)) goto parse_shaozhuangfen;
        break;
      }

      // repeated int32 shaozhuangfen = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_shaozhuangfen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24, input, this->mutable_shaozhuangfen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_shaozhuangfen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_shaozhuangfen;
        if (input->ExpectTag(32)) goto parse_mapaifen;
        break;
      }

      // repeated int32 mapaifen = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_mapaifen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_mapaifen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_mapaifen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_mapaifen;
        if (input->ExpectTag(40)) goto parse_jingfen;
        break;
      }

      // repeated int32 jingfen = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_jingfen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 40, input, this->mutable_jingfen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_jingfen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_jingfen;
        if (input->ExpectTag(48)) goto parse_gangfen;
        break;
      }

      // repeated int32 gangfen = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_gangfen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48, input, this->mutable_gangfen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_gangfen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_gangfen;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DongXiangGameEnd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 hufen = 1;
  for (int i = 0; i < this->hufen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->hufen(i), output);
  }

  // repeated int32 genzhuangfen = 2;
  for (int i = 0; i < this->genzhuangfen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->genzhuangfen(i), output);
  }

  // repeated int32 shaozhuangfen = 3;
  for (int i = 0; i < this->shaozhuangfen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->shaozhuangfen(i), output);
  }

  // repeated int32 mapaifen = 4;
  for (int i = 0; i < this->mapaifen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->mapaifen(i), output);
  }

  // repeated int32 jingfen = 5;
  for (int i = 0; i < this->jingfen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      5, this->jingfen(i), output);
  }

  // repeated int32 gangfen = 6;
  for (int i = 0; i < this->gangfen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->gangfen(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DongXiangGameEnd::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 hufen = 1;
  for (int i = 0; i < this->hufen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->hufen(i), target);
  }

  // repeated int32 genzhuangfen = 2;
  for (int i = 0; i < this->genzhuangfen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->genzhuangfen(i), target);
  }

  // repeated int32 shaozhuangfen = 3;
  for (int i = 0; i < this->shaozhuangfen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(3, this->shaozhuangfen(i), target);
  }

  // repeated int32 mapaifen = 4;
  for (int i = 0; i < this->mapaifen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->mapaifen(i), target);
  }

  // repeated int32 jingfen = 5;
  for (int i = 0; i < this->jingfen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(5, this->jingfen(i), target);
  }

  // repeated int32 gangfen = 6;
  for (int i = 0; i < this->gangfen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(6, this->gangfen(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DongXiangGameEnd::ByteSize() const {
  int total_size = 0;

  // repeated int32 hufen = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->hufen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->hufen(i));
    }
    total_size += 1 * this->hufen_size() + data_size;
  }

  // repeated int32 genzhuangfen = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->genzhuangfen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->genzhuangfen(i));
    }
    total_size += 1 * this->genzhuangfen_size() + data_size;
  }

  // repeated int32 shaozhuangfen = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->shaozhuangfen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->shaozhuangfen(i));
    }
    total_size += 1 * this->shaozhuangfen_size() + data_size;
  }

  // repeated int32 mapaifen = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->mapaifen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->mapaifen(i));
    }
    total_size += 1 * this->mapaifen_size() + data_size;
  }

  // repeated int32 jingfen = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->jingfen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->jingfen(i));
    }
    total_size += 1 * this->jingfen_size() + data_size;
  }

  // repeated int32 gangfen = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->gangfen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->gangfen(i));
    }
    total_size += 1 * this->gangfen_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DongXiangGameEnd::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DongXiangGameEnd* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DongXiangGameEnd*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DongXiangGameEnd::MergeFrom(const DongXiangGameEnd& from) {
  GOOGLE_CHECK_NE(&from, this);
  hufen_.MergeFrom(from.hufen_);
  genzhuangfen_.MergeFrom(from.genzhuangfen_);
  shaozhuangfen_.MergeFrom(from.shaozhuangfen_);
  mapaifen_.MergeFrom(from.mapaifen_);
  jingfen_.MergeFrom(from.jingfen_);
  gangfen_.MergeFrom(from.gangfen_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DongXiangGameEnd::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DongXiangGameEnd::CopyFrom(const DongXiangGameEnd& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DongXiangGameEnd::IsInitialized() const {

  return true;
}

void DongXiangGameEnd::Swap(DongXiangGameEnd* other) {
  if (other != this) {
    hufen_.Swap(&other->hufen_);
    genzhuangfen_.Swap(&other->genzhuangfen_);
    shaozhuangfen_.Swap(&other->shaozhuangfen_);
    mapaifen_.Swap(&other->mapaifen_);
    jingfen_.Swap(&other->jingfen_);
    gangfen_.Swap(&other->gangfen_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DongXiangGameEnd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DongXiangGameEnd_descriptor_;
  metadata.reflection = DongXiangGameEnd_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dongxiang
}  // namespace game
}  // namespace proto

// @@protoc_insertion_point(global_scope)
