// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: anqinggameproto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "anqinggameproto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace anqingmj {

namespace {

const ::google::protobuf::Descriptor* AnQingGameEnd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AnQingGameEnd_reflection_ = NULL;
const ::google::protobuf::Descriptor* HuaCard_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HuaCard_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_anqinggameproto_2eproto() {
  protobuf_AddDesc_anqinggameproto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "anqinggameproto.proto");
  GOOGLE_CHECK(file != NULL);
  AnQingGameEnd_descriptor_ = file->message_type(0);
  static const int AnQingGameEnd_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, buhuanum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, huacards_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, sanfengnum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, gangfen_),
  };
  AnQingGameEnd_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AnQingGameEnd_descriptor_,
      AnQingGameEnd::default_instance_,
      AnQingGameEnd_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AnQingGameEnd, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AnQingGameEnd));
  HuaCard_descriptor_ = file->message_type(1);
  static const int HuaCard_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HuaCard, card_),
  };
  HuaCard_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HuaCard_descriptor_,
      HuaCard::default_instance_,
      HuaCard_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HuaCard, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HuaCard, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HuaCard));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_anqinggameproto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AnQingGameEnd_descriptor_, &AnQingGameEnd::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HuaCard_descriptor_, &HuaCard::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_anqinggameproto_2eproto() {
  delete AnQingGameEnd::default_instance_;
  delete AnQingGameEnd_reflection_;
  delete HuaCard::default_instance_;
  delete HuaCard_reflection_;
}

void protobuf_AddDesc_anqinggameproto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025anqinggameproto.proto\022\023proto.game.anqi"
    "ngmj\"v\n\rAnQingGameEnd\022\020\n\010BuHuaNum\030\001 \003(\005\022"
    ".\n\010huaCards\030\002 \003(\0132\034.proto.game.anqingmj."
    "HuaCard\022\022\n\nSanFengNum\030\003 \003(\005\022\017\n\007GangFen\030\004"
    " \003(\005\"\027\n\007HuaCard\022\014\n\004Card\030\001 \003(\005", 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "anqinggameproto.proto", &protobuf_RegisterTypes);
  AnQingGameEnd::default_instance_ = new AnQingGameEnd();
  HuaCard::default_instance_ = new HuaCard();
  AnQingGameEnd::default_instance_->InitAsDefaultInstance();
  HuaCard::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_anqinggameproto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_anqinggameproto_2eproto {
  StaticDescriptorInitializer_anqinggameproto_2eproto() {
    protobuf_AddDesc_anqinggameproto_2eproto();
  }
} static_descriptor_initializer_anqinggameproto_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AnQingGameEnd::kBuHuaNumFieldNumber;
const int AnQingGameEnd::kHuaCardsFieldNumber;
const int AnQingGameEnd::kSanFengNumFieldNumber;
const int AnQingGameEnd::kGangFenFieldNumber;
#endif  // !_MSC_VER

AnQingGameEnd::AnQingGameEnd()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AnQingGameEnd::InitAsDefaultInstance() {
}

AnQingGameEnd::AnQingGameEnd(const AnQingGameEnd& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AnQingGameEnd::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AnQingGameEnd::~AnQingGameEnd() {
  SharedDtor();
}

void AnQingGameEnd::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AnQingGameEnd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AnQingGameEnd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AnQingGameEnd_descriptor_;
}

const AnQingGameEnd& AnQingGameEnd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_anqinggameproto_2eproto();
  return *default_instance_;
}

AnQingGameEnd* AnQingGameEnd::default_instance_ = NULL;

AnQingGameEnd* AnQingGameEnd::New() const {
  return new AnQingGameEnd;
}

void AnQingGameEnd::Clear() {
  buhuanum_.Clear();
  huacards_.Clear();
  sanfengnum_.Clear();
  gangfen_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AnQingGameEnd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 BuHuaNum = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_BuHuaNum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_buhuanum())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_buhuanum())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_BuHuaNum;
        if (input->ExpectTag(18)) goto parse_huaCards;
        break;
      }

      // repeated .proto.game.anqingmj.HuaCard huaCards = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_huaCards:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_huacards()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_huaCards;
        if (input->ExpectTag(24)) goto parse_SanFengNum;
        break;
      }

      // repeated int32 SanFengNum = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_SanFengNum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24, input, this->mutable_sanfengnum())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_sanfengnum())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_SanFengNum;
        if (input->ExpectTag(32)) goto parse_GangFen;
        break;
      }

      // repeated int32 GangFen = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_GangFen:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32, input, this->mutable_gangfen())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_gangfen())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_GangFen;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AnQingGameEnd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 BuHuaNum = 1;
  for (int i = 0; i < this->buhuanum_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->buhuanum(i), output);
  }

  // repeated .proto.game.anqingmj.HuaCard huaCards = 2;
  for (int i = 0; i < this->huacards_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->huacards(i), output);
  }

  // repeated int32 SanFengNum = 3;
  for (int i = 0; i < this->sanfengnum_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->sanfengnum(i), output);
  }

  // repeated int32 GangFen = 4;
  for (int i = 0; i < this->gangfen_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->gangfen(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AnQingGameEnd::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 BuHuaNum = 1;
  for (int i = 0; i < this->buhuanum_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->buhuanum(i), target);
  }

  // repeated .proto.game.anqingmj.HuaCard huaCards = 2;
  for (int i = 0; i < this->huacards_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->huacards(i), target);
  }

  // repeated int32 SanFengNum = 3;
  for (int i = 0; i < this->sanfengnum_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(3, this->sanfengnum(i), target);
  }

  // repeated int32 GangFen = 4;
  for (int i = 0; i < this->gangfen_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(4, this->gangfen(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AnQingGameEnd::ByteSize() const {
  int total_size = 0;

  // repeated int32 BuHuaNum = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->buhuanum_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->buhuanum(i));
    }
    total_size += 1 * this->buhuanum_size() + data_size;
  }

  // repeated .proto.game.anqingmj.HuaCard huaCards = 2;
  total_size += 1 * this->huacards_size();
  for (int i = 0; i < this->huacards_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->huacards(i));
  }

  // repeated int32 SanFengNum = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->sanfengnum_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->sanfengnum(i));
    }
    total_size += 1 * this->sanfengnum_size() + data_size;
  }

  // repeated int32 GangFen = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->gangfen_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->gangfen(i));
    }
    total_size += 1 * this->gangfen_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AnQingGameEnd::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AnQingGameEnd* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AnQingGameEnd*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AnQingGameEnd::MergeFrom(const AnQingGameEnd& from) {
  GOOGLE_CHECK_NE(&from, this);
  buhuanum_.MergeFrom(from.buhuanum_);
  huacards_.MergeFrom(from.huacards_);
  sanfengnum_.MergeFrom(from.sanfengnum_);
  gangfen_.MergeFrom(from.gangfen_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AnQingGameEnd::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AnQingGameEnd::CopyFrom(const AnQingGameEnd& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AnQingGameEnd::IsInitialized() const {

  return true;
}

void AnQingGameEnd::Swap(AnQingGameEnd* other) {
  if (other != this) {
    buhuanum_.Swap(&other->buhuanum_);
    huacards_.Swap(&other->huacards_);
    sanfengnum_.Swap(&other->sanfengnum_);
    gangfen_.Swap(&other->gangfen_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AnQingGameEnd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AnQingGameEnd_descriptor_;
  metadata.reflection = AnQingGameEnd_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HuaCard::kCardFieldNumber;
#endif  // !_MSC_VER

HuaCard::HuaCard()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HuaCard::InitAsDefaultInstance() {
}

HuaCard::HuaCard(const HuaCard& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HuaCard::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HuaCard::~HuaCard() {
  SharedDtor();
}

void HuaCard::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HuaCard::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HuaCard::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HuaCard_descriptor_;
}

const HuaCard& HuaCard::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_anqinggameproto_2eproto();
  return *default_instance_;
}

HuaCard* HuaCard::default_instance_ = NULL;

HuaCard* HuaCard::New() const {
  return new HuaCard;
}

void HuaCard::Clear() {
  card_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HuaCard::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 Card = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Card:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_card())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_card())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_Card;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HuaCard::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 Card = 1;
  for (int i = 0; i < this->card_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->card(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HuaCard::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 Card = 1;
  for (int i = 0; i < this->card_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->card(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HuaCard::ByteSize() const {
  int total_size = 0;

  // repeated int32 Card = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->card_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->card(i));
    }
    total_size += 1 * this->card_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HuaCard::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HuaCard* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HuaCard*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HuaCard::MergeFrom(const HuaCard& from) {
  GOOGLE_CHECK_NE(&from, this);
  card_.MergeFrom(from.card_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HuaCard::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HuaCard::CopyFrom(const HuaCard& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HuaCard::IsInitialized() const {

  return true;
}

void HuaCard::Swap(HuaCard* other) {
  if (other != this) {
    card_.Swap(&other->card_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HuaCard::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HuaCard_descriptor_;
  metadata.reflection = HuaCard_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace anqingmj
}  // namespace game
}  // namespace proto

// @@protoc_insertion_point(global_scope)
